app = "hocuspocus-server"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[services]]
  internal_port = 1234
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
